"""
Multi-Domain Theta Framework

This module extends theta beyond physics to economics, game theory,
information theory, complex systems, quantum computing, quantum biology,
cosmology, education, mechanical systems, networks, cognition, social
dynamics, and chemistry.

Key Insight: Theta represents a universal interpolation parameter
between discrete/quantum-like and continuous/classical behavior
across ALL domains exhibiting phase transitions.

Original Domains:
- economics: Ising model of markets, phase transitions
- information: Shannon vs von Neumann entropy
- game_theory: Entanglement parameter in quantum games
- complex_systems: Critical exponents, social phase transitions
- quantum_computing: Error thresholds, decoherence
- quantum_biology: Coherence in photosynthesis, tunneling in enzymes
- cosmology: Theta evolution from Big Bang to heat death

New Domains (2024):
- education: Learning curves, memory retention, knowledge integration
- mechanical_systems: Engine efficiency, motors, batteries, damping
- networks: Shannon capacity, percolation, QKD
- cognition: Integrated information, neural criticality, working memory
- social_systems: Opinion dynamics, epidemics, urban scaling, traffic
- chemistry: Superconductivity, BEC, quantum dots, superfluidity
- work_life_balance: Burnout, effort-reward, work-family conflict

Each domain maps to the universal theta framework:
    theta = 0: Classical limit (random, independent, deterministic)
    theta = 1: Quantum limit (correlated, entangled, coherent)
"""

from .economics import (
    MarketSystem,
    IsingMarket,
    compute_market_theta,
    ECONOMIC_SYSTEMS,
    compute_coupling_from_correlation,
    detect_phase_transition,
)

from .information import (
    InformationSystem,
    compute_shannon_entropy,
    compute_von_neumann_entropy,
    compute_purity,
    compute_information_theta,
    INFORMATION_SYSTEMS,
)

from .game_theory import (
    QuantumGame,
    compute_entanglement_theta,
    GAME_SYSTEMS,
    prisoners_dilemma_payoff,
)

from .complex_systems import (
    ComplexSystem,
    CriticalExponents,
    compute_order_parameter,
    compute_susceptibility,
    compute_correlation_length,
    detect_critical_point,
    compute_complex_theta,
    COMPLEX_SYSTEMS,
)

from .quantum_computing import (
    QubitSystem,
    compute_coherence_theta,
    compute_error_threshold_theta,
    compute_quantum_computing_theta,
    QUANTUM_HARDWARE,
)

from .quantum_biology import (
    BiologicalSystem,
    compute_quantum_bio_theta,
    compute_tunneling_theta,
    BIOLOGICAL_SYSTEMS,
)

from .cosmology import (
    CosmicEpoch,
    compute_cosmic_theta,
    compute_thermal_theta,
    COSMIC_TIMELINE,
)

from .control_theory import (
    ControlSystem,
    ControllerType,
    StabilityRegime,
    compute_control_theta,
    compute_gain_margin_theta,
    compute_phase_margin_theta,
    classify_stability,
    CONTROL_SYSTEMS,
)

from .nonlinear_dynamics import (
    DynamicalSystem,
    DynamicalRegime,
    AttractorType,
    compute_dynamics_theta,
    compute_lyapunov_theta,
    classify_regime as classify_dynamics_regime,
    logistic_map,
    logistic_lyapunov,
    DYNAMICAL_SYSTEMS,
    FEIGENBAUM_DELTA,
    FEIGENBAUM_ALPHA,
)

from .quantum_gravity import (
    QuantumGravitySystem,
    SpacetimeRegime,
    QuantumGravityTheory,
    compute_quantum_gravity_theta,
    compute_length_theta,
    compute_energy_theta,
    classify_regime as classify_spacetime_regime,
    black_hole_theta,
    hawking_temperature_k,
    bekenstein_entropy,
    QUANTUM_GRAVITY_SYSTEMS,
    L_PLANCK,
    E_PLANCK_EV,
    M_PLANCK,
)

from .universal import (
    UniversalTheta,
    DomainType,
    cross_domain_comparison,
)

# New domains (2024)
from .education import (
    LearningSystem,
    LearningPhase,
    MemoryRetention,
    LearningCurve,
    compute_education_theta,
    compute_retention_theta,
    compute_learning_theta,
    classify_learning_phase,
    ebbinghaus_retention,
    EDUCATION_SYSTEMS,
)

from .mechanical_systems import (
    MechanicalSystem,
    SystemType,
    EfficiencyRegime,
    compute_mechanical_theta,
    compute_engine_theta,
    compute_motor_theta,
    compute_battery_theta,
    compute_damping_theta,
    carnot_efficiency,
    MECHANICAL_SYSTEMS,
)

from .networks import (
    NetworkSystem,
    NetworkType,
    ConnectivityRegime,
    compute_network_theta,
    compute_shannon_theta,
    compute_percolation_theta,
    compute_qkd_theta,
    shannon_capacity,
    percolation_threshold,
    NETWORK_SYSTEMS,
)

from .cognition import (
    CognitiveSystem,
    ConsciousnessState,
    BrainState,
    compute_cognition_theta,
    compute_phi_ratio,
    compute_criticality_theta,
    compute_working_memory_theta,
    classify_brain_state,
    COGNITIVE_SYSTEMS,
)

from .social_systems import (
    SocialSystem,
    SocialPhase,
    EpidemicPhase,
    TrafficPhase,
    compute_social_theta,
    compute_opinion_theta,
    compute_epidemic_theta,
    compute_urban_theta,
    compute_traffic_theta,
    classify_social_phase,
    herd_immunity_threshold,
    SOCIAL_SYSTEMS,
)

from .chemistry import (
    QuantumMaterial,
    MaterialPhase,
    SuperconductorType,
    compute_chemistry_theta,
    compute_superconductor_theta,
    compute_bec_theta,
    compute_quantum_dot_theta,
    compute_superfluid_theta,
    bcs_gap_zero_temp,
    bec_condensate_fraction,
    SUPERCONDUCTORS,
)

from .work_life_balance import (
    WorkLifeSystem,
    WellbeingPhase,
    BurnoutDimension,
    ConflictDirection,
    compute_burnout_theta,
    compute_effort_reward_theta,
    compute_work_family_conflict_theta,
    compute_cognitive_load_theta,
    compute_jdr_theta,
    compute_recovery_theta,
    compute_job_strain_theta,
    compute_work_life_theta,
    classify_burnout,
    classify_wellbeing_phase,
    classify_job_strain,
    WORK_LIFE_SYSTEMS,
)

# New domains (2025)
from .cybersecurity import (
    SecuritySystem,
    SecurityPosture,
    ThreatLevel,
    CryptoStrength,
    compute_attack_surface_theta,
    compute_detection_theta,
    compute_response_theta,
    compute_defense_depth_theta,
    compute_crypto_theta,
    compute_security_theta,
    classify_security_posture,
    SECURITY_SYSTEMS,
)

from .ai_ml import (
    MLSystem,
    ModelArchitecture,
    LearningRegime,
    AttentionType,
    compute_generalization_theta,
    compute_gradient_theta,
    compute_attention_theta,
    compute_ml_theta,
    classify_learning_regime,
    ML_SYSTEMS,
)

from .category_theory import (
    CategoricalSystem,
    AbstractionLevel,
    MorphismType,
    compute_abstraction_theta,
    compute_functoriality_theta,
    compute_naturality_theta,
    compute_universality_theta,
    compute_coherence_theta as compute_cat_coherence_theta,
    compute_category_theta,
    classify_abstraction_regime,
    CATEGORY_SYSTEMS,
)

from .semantic_structure import (
    SemanticSystem,
    SemanticCoherence,
    StructureFormat,
    compute_coherence_theta as compute_semantic_coherence_theta,
    compute_connectivity_theta,
    compute_disambiguation_theta,
    compute_grounding_theta,
    compute_semantic_theta,
    classify_semantic_coherence,
    SEMANTIC_SYSTEMS,
)

from .recursive_learning import (
    RecursiveSystem,
    RecursionLevel,
    ImprovementType,
    compute_meta_awareness_theta,
    compute_improvement_theta,
    compute_recursion_theta,
    compute_feedback_theta,
    compute_recursive_theta,
    classify_recursion_level,
    RECURSIVE_SYSTEMS,
)

# New domains (2026) - Arxiiv integration
from .quantum_foundations import (
    QuantumFoundationSystem,
    DecoherenceRegime,
    MeasurementType,
    QuantumClassicalMechanism,
    PointerBasis,
    compute_decoherence_theta,
    compute_measurement_theta,
    compute_zurek_decoherence_time,
    compute_penrose_time,
    compute_quantum_foundations_theta,
    classify_decoherence_regime,
    thermal_time,
    thermal_wavelength,
    QUANTUM_FOUNDATIONS_SYSTEMS,
)

from .cognitive_neuro import (
    NeuroCognitiveSystem,
    AttentionState,
    MetacognitiveLevel,
    WorkingMemoryPhase,
    ExecutiveMode,
    ConsciousnessLevel,
    compute_attention_theta as compute_neuro_attention_theta,
    compute_metacognition_theta,
    compute_wm_theta,
    compute_executive_theta,
    compute_arousal_theta,
    compute_global_workspace_theta,
    compute_cognitive_neuro_theta,
    classify_attention_state,
    classify_metacognition_level,
    classify_wm_phase,
    classify_executive_mode,
    classify_consciousness_level,
    COGNITIVE_NEURO_SYSTEMS,
    COWAN_LIMIT,
    MILLER_LIMIT,
)

from .physics_extended import (
    PhysicsExtendedSystem,
    GRRegime,
    HEPTheoryRegime,
    BSMScale,
    QuantumGravityRegime,
    SpacetimeType,
    compute_gr_theta,
    compute_curvature_theta,
    compute_hep_th_theta,
    compute_hep_ph_theta,
    compute_quantum_gravity_theta as compute_qg_theta,
    compute_holographic_theta,
    compute_physics_extended_theta,
    classify_gr_regime,
    classify_hep_th_regime,
    classify_bsm_scale,
    classify_quantum_gravity_regime,
    schwarzschild_radius,
    hawking_temperature,
    PHYSICS_EXTENDED_SYSTEMS,
)

# New domains (2026) - Phase 2 Arxiiv integration
from .condensed_matter import (
    CondensedMatterSystem,
    PhaseRegime,
    TransportType,
    DisorderLevel,
    TopologicalPhase as CMTopologicalPhase,
    CriticalExponentClass,
    compute_phase_theta,
    compute_order_theta,
    compute_localization_theta,
    compute_transport_theta,
    compute_hall_theta,
    compute_correlation_theta,
    compute_topological_theta as compute_cm_topological_theta,
    compute_condensed_matter_theta,
    classify_phase_regime,
    classify_transport,
    classify_disorder,
    classify_topological as classify_cm_topological,
    CONDENSED_MATTER_SYSTEMS,
    ISING_2D_TC,
    ANDERSON_WC_3D,
)

from .information_systems import (
    InformationSystemState,
    RetrievalQuality,
    AutonomyLevel,
    RenderingFidelity,
    CodeQuality,
    SystemDomain,
    compute_retrieval_theta,
    compute_ndcg_theta,
    compute_autonomy_theta,
    compute_graphics_theta,
    compute_rendering_theta,
    compute_code_theta,
    compute_latency_theta,
    compute_information_system_theta,
    classify_retrieval_quality,
    classify_autonomy_level,
    classify_rendering_fidelity,
    classify_code_quality,
    INFORMATION_SYSTEMS as INFO_SYSTEMS,
    IDEAL_LATENCY_MS,
    TARGET_FPS,
)

from .ux_accessibility import (
    UXAccessibilitySystem,
    AccessibilityLevel,
    CognitiveLoadState,
    UsabilityLevel,
    InteractionMode,
    ReadabilityLevel,
    compute_accessibility_theta,
    compute_usability_theta,
    compute_cognitive_theta,
    compute_comprehension_theta,
    compute_task_theta,
    compute_inclusive_theta,
    compute_ux_accessibility_theta,
    classify_accessibility_level,
    classify_cognitive_load,
    classify_usability,
    classify_readability,
    classify_interaction_mode,
    UX_ACCESSIBILITY_SYSTEMS,
    SUS_AVERAGE,
    WCAG_AA_CONTRAST,
    WCAG_AAA_CONTRAST,
)

from .advanced_mathematics import (
    MathematicalSystem,
    TopologicalPhase as MathTopologicalPhase,
    GeometricRegime,
    IntegrabilityLevel,
    SymmetryType,
    ManifoldType,
    compute_topological_theta,
    compute_euler_theta,
    compute_curvature_theta as compute_math_curvature_theta,
    compute_integrability_theta,
    compute_symmetry_theta,
    compute_homotopy_theta,
    compute_math_theta,
    classify_topological_phase,
    classify_geometric_regime,
    classify_integrability,
    classify_symmetry,
    MATHEMATICAL_SYSTEMS,
    EULER_MASCHERONI,
    FEIGENBAUM_DELTA as MATH_FEIGENBAUM_DELTA,
    APERY_CONSTANT,
)

# New domains (2026) - Phase 3 Arxiiv integration
from .high_energy_physics import (
    HEPSystem,
    ParticleRegime,
    LatticeRegime,
    ExperimentType,
    ChiralRegime,
    compute_qcd_coupling_theta,
    compute_lattice_theta,
    compute_confinement_theta,
    compute_chiral_theta,
    compute_hep_theta,
    running_alpha_s,
    classify_particle_regime,
    classify_lattice_regime,
    HEP_SYSTEMS,
)

from .atomic_optical_physics import (
    AtomicOpticalSystem,
    AtomicRegime,
    OpticalPhase,
    TrapType,
    CoolingRegime,
    compute_rabi_theta,
    compute_cooperativity_theta,
    compute_optical_depth_theta,
    compute_squeezing_theta,
    compute_cooling_theta,
    compute_atomic_optical_theta,
    classify_atomic_regime,
    ATOMIC_OPTICAL_SYSTEMS,
)

from .pure_mathematics import (
    PureMathSystem,
    AlgebraicComplexity,
    RepresentationType,
    FunctionalClass,
    CombinatorialPhase,
    compute_genus_theta,
    compute_singularity_theta,
    compute_rank_theta,
    compute_spectral_theta,
    compute_pure_math_theta,
    classify_algebraic_complexity,
    PURE_MATH_SYSTEMS,
)

from .applied_mathematics import (
    AppliedMathSystem,
    PDEType,
    OptimizationClass,
    ConvergenceType,
    StabilityClass,
    compute_regularity_theta,
    compute_stability_theta,
    compute_convergence_theta,
    compute_condition_theta,
    compute_applied_math_theta,
    classify_pde_type,
    classify_optimization,
    APPLIED_MATH_SYSTEMS,
)

from .distributed_systems import (
    DistributedSystem,
    ConsistencyLevel,
    PartitionTolerance,
    ScalabilityClass,
    ReplicationMode,
    compute_consistency_theta,
    compute_availability_theta,
    compute_latency_theta as compute_distributed_latency_theta,
    compute_partition_theta,
    compute_distributed_theta,
    classify_consistency,
    DISTRIBUTED_SYSTEMS,
)

from .signal_processing import (
    SignalSystem,
    SignalQuality,
    ProcessingDomain,
    CompressionLevel,
    FilterType,
    compute_snr_theta,
    compute_compression_theta,
    compute_sparsity_theta,
    compute_signal_theta,
    classify_signal_quality,
    SIGNAL_SYSTEMS,
)

from .electromagnetic import (
    PhotonSystem,
    EMBand,
    PhotonRegime,
    compute_em_theta,
    compute_wavelength_theta,
    compute_frequency_theta,
    classify_photon_regime,
    classify_em_band,
    wien_displacement_wavelength,
    planck_spectral_radiance,
    photon_occupation_number,
    EM_SPECTRUM,
    C as SPEED_OF_LIGHT,
    HC_EV_NM,
    KT_300K_EV,
)

__all__ = [
    # Economics
    "MarketSystem",
    "IsingMarket",
    "compute_market_theta",
    "ECONOMIC_SYSTEMS",
    "compute_coupling_from_correlation",
    "detect_phase_transition",
    # Information
    "InformationSystem",
    "compute_shannon_entropy",
    "compute_von_neumann_entropy",
    "compute_purity",
    "compute_information_theta",
    "INFORMATION_SYSTEMS",
    # Game Theory
    "QuantumGame",
    "compute_entanglement_theta",
    "GAME_SYSTEMS",
    "prisoners_dilemma_payoff",
    # Complex Systems
    "ComplexSystem",
    "CriticalExponents",
    "compute_order_parameter",
    "compute_susceptibility",
    "compute_correlation_length",
    "detect_critical_point",
    "compute_complex_theta",
    "COMPLEX_SYSTEMS",
    # Quantum Computing
    "QubitSystem",
    "compute_coherence_theta",
    "compute_error_threshold_theta",
    "compute_quantum_computing_theta",
    "QUANTUM_HARDWARE",
    # Quantum Biology
    "BiologicalSystem",
    "compute_quantum_bio_theta",
    "compute_tunneling_theta",
    "BIOLOGICAL_SYSTEMS",
    # Cosmology
    "CosmicEpoch",
    "compute_cosmic_theta",
    "compute_thermal_theta",
    "COSMIC_TIMELINE",
    # Control Theory
    "ControlSystem",
    "ControllerType",
    "StabilityRegime",
    "compute_control_theta",
    "compute_gain_margin_theta",
    "compute_phase_margin_theta",
    "classify_stability",
    "CONTROL_SYSTEMS",
    # Nonlinear Dynamics
    "DynamicalSystem",
    "DynamicalRegime",
    "AttractorType",
    "compute_dynamics_theta",
    "compute_lyapunov_theta",
    "classify_dynamics_regime",
    "logistic_map",
    "logistic_lyapunov",
    "DYNAMICAL_SYSTEMS",
    "FEIGENBAUM_DELTA",
    "FEIGENBAUM_ALPHA",
    # Quantum Gravity
    "QuantumGravitySystem",
    "SpacetimeRegime",
    "QuantumGravityTheory",
    "compute_quantum_gravity_theta",
    "compute_length_theta",
    "compute_energy_theta",
    "classify_spacetime_regime",
    "black_hole_theta",
    "hawking_temperature_k",
    "bekenstein_entropy",
    "QUANTUM_GRAVITY_SYSTEMS",
    "L_PLANCK",
    "E_PLANCK_EV",
    "M_PLANCK",
    # Universal
    "UniversalTheta",
    "DomainType",
    "cross_domain_comparison",
    # Education
    "LearningSystem",
    "LearningPhase",
    "MemoryRetention",
    "LearningCurve",
    "compute_education_theta",
    "compute_retention_theta",
    "compute_learning_theta",
    "classify_learning_phase",
    "ebbinghaus_retention",
    "EDUCATION_SYSTEMS",
    # Mechanical Systems
    "MechanicalSystem",
    "SystemType",
    "EfficiencyRegime",
    "compute_mechanical_theta",
    "compute_engine_theta",
    "compute_motor_theta",
    "compute_battery_theta",
    "compute_damping_theta",
    "carnot_efficiency",
    "MECHANICAL_SYSTEMS",
    # Networks
    "NetworkSystem",
    "NetworkType",
    "ConnectivityRegime",
    "compute_network_theta",
    "compute_shannon_theta",
    "compute_percolation_theta",
    "compute_qkd_theta",
    "shannon_capacity",
    "percolation_threshold",
    "NETWORK_SYSTEMS",
    # Cognition
    "CognitiveSystem",
    "ConsciousnessState",
    "BrainState",
    "compute_cognition_theta",
    "compute_phi_ratio",
    "compute_criticality_theta",
    "compute_working_memory_theta",
    "classify_brain_state",
    "COGNITIVE_SYSTEMS",
    # Social Systems
    "SocialSystem",
    "SocialPhase",
    "EpidemicPhase",
    "TrafficPhase",
    "compute_social_theta",
    "compute_opinion_theta",
    "compute_epidemic_theta",
    "compute_urban_theta",
    "compute_traffic_theta",
    "classify_social_phase",
    "herd_immunity_threshold",
    "SOCIAL_SYSTEMS",
    # Chemistry
    "QuantumMaterial",
    "MaterialPhase",
    "SuperconductorType",
    "compute_chemistry_theta",
    "compute_superconductor_theta",
    "compute_bec_theta",
    "compute_quantum_dot_theta",
    "compute_superfluid_theta",
    "bcs_gap_zero_temp",
    "bec_condensate_fraction",
    "SUPERCONDUCTORS",
    # Work-Life Balance
    "WorkLifeSystem",
    "WellbeingPhase",
    "BurnoutDimension",
    "ConflictDirection",
    "compute_burnout_theta",
    "compute_effort_reward_theta",
    "compute_work_family_conflict_theta",
    "compute_cognitive_load_theta",
    "compute_jdr_theta",
    "compute_recovery_theta",
    "compute_job_strain_theta",
    "compute_work_life_theta",
    "classify_burnout",
    "classify_wellbeing_phase",
    "classify_job_strain",
    "WORK_LIFE_SYSTEMS",
    # Cybersecurity
    "SecuritySystem",
    "SecurityPosture",
    "ThreatLevel",
    "CryptoStrength",
    "compute_attack_surface_theta",
    "compute_detection_theta",
    "compute_response_theta",
    "compute_defense_depth_theta",
    "compute_crypto_theta",
    "compute_security_theta",
    "classify_security_posture",
    "SECURITY_SYSTEMS",
    # AI/ML
    "MLSystem",
    "ModelArchitecture",
    "LearningRegime",
    "AttentionType",
    "compute_generalization_theta",
    "compute_gradient_theta",
    "compute_attention_theta",
    "compute_ml_theta",
    "classify_learning_regime",
    "ML_SYSTEMS",
    # Category Theory
    "CategoricalSystem",
    "AbstractionLevel",
    "MorphismType",
    "compute_abstraction_theta",
    "compute_functoriality_theta",
    "compute_naturality_theta",
    "compute_universality_theta",
    "compute_cat_coherence_theta",
    "compute_category_theta",
    "classify_abstraction_regime",
    "CATEGORY_SYSTEMS",
    # Semantic Structure
    "SemanticSystem",
    "SemanticCoherence",
    "StructureFormat",
    "compute_semantic_coherence_theta",
    "compute_connectivity_theta",
    "compute_disambiguation_theta",
    "compute_grounding_theta",
    "compute_semantic_theta",
    "classify_semantic_coherence",
    "SEMANTIC_SYSTEMS",
    # Recursive Learning
    "RecursiveSystem",
    "RecursionLevel",
    "ImprovementType",
    "compute_meta_awareness_theta",
    "compute_improvement_theta",
    "compute_recursion_theta",
    "compute_feedback_theta",
    "compute_recursive_theta",
    "classify_recursion_level",
    "RECURSIVE_SYSTEMS",
    # Quantum Foundations (2026)
    "QuantumFoundationSystem",
    "DecoherenceRegime",
    "MeasurementType",
    "QuantumClassicalMechanism",
    "PointerBasis",
    "compute_decoherence_theta",
    "compute_measurement_theta",
    "compute_zurek_decoherence_time",
    "compute_penrose_time",
    "compute_quantum_foundations_theta",
    "classify_decoherence_regime",
    "thermal_time",
    "thermal_wavelength",
    "QUANTUM_FOUNDATIONS_SYSTEMS",
    # Cognitive Neuroscience (2026)
    "NeuroCognitiveSystem",
    "AttentionState",
    "MetacognitiveLevel",
    "WorkingMemoryPhase",
    "ExecutiveMode",
    "ConsciousnessLevel",
    "compute_neuro_attention_theta",
    "compute_metacognition_theta",
    "compute_wm_theta",
    "compute_executive_theta",
    "compute_arousal_theta",
    "compute_global_workspace_theta",
    "compute_cognitive_neuro_theta",
    "classify_attention_state",
    "classify_metacognition_level",
    "classify_wm_phase",
    "classify_executive_mode",
    "classify_consciousness_level",
    "COGNITIVE_NEURO_SYSTEMS",
    "COWAN_LIMIT",
    "MILLER_LIMIT",
    # Physics Extended (2026)
    "PhysicsExtendedSystem",
    "GRRegime",
    "HEPTheoryRegime",
    "BSMScale",
    "QuantumGravityRegime",
    "SpacetimeType",
    "compute_gr_theta",
    "compute_curvature_theta",
    "compute_hep_th_theta",
    "compute_hep_ph_theta",
    "compute_qg_theta",
    "compute_holographic_theta",
    "compute_physics_extended_theta",
    "classify_gr_regime",
    "classify_hep_th_regime",
    "classify_bsm_scale",
    "classify_quantum_gravity_regime",
    "schwarzschild_radius",
    "hawking_temperature",
    "PHYSICS_EXTENDED_SYSTEMS",
    # Condensed Matter (2026)
    "CondensedMatterSystem",
    "PhaseRegime",
    "TransportType",
    "DisorderLevel",
    "CMTopologicalPhase",
    "CriticalExponentClass",
    "compute_phase_theta",
    "compute_order_theta",
    "compute_localization_theta",
    "compute_transport_theta",
    "compute_hall_theta",
    "compute_correlation_theta",
    "compute_cm_topological_theta",
    "compute_condensed_matter_theta",
    "classify_phase_regime",
    "classify_transport",
    "classify_disorder",
    "classify_cm_topological",
    "CONDENSED_MATTER_SYSTEMS",
    "ISING_2D_TC",
    "ANDERSON_WC_3D",
    # Information Systems (2026)
    "InformationSystemState",
    "RetrievalQuality",
    "AutonomyLevel",
    "RenderingFidelity",
    "CodeQuality",
    "SystemDomain",
    "compute_retrieval_theta",
    "compute_ndcg_theta",
    "compute_autonomy_theta",
    "compute_graphics_theta",
    "compute_rendering_theta",
    "compute_code_theta",
    "compute_latency_theta",
    "compute_information_system_theta",
    "classify_retrieval_quality",
    "classify_autonomy_level",
    "classify_rendering_fidelity",
    "classify_code_quality",
    "INFO_SYSTEMS",
    "IDEAL_LATENCY_MS",
    "TARGET_FPS",
    # UX/Accessibility (2026)
    "UXAccessibilitySystem",
    "AccessibilityLevel",
    "CognitiveLoadState",
    "UsabilityLevel",
    "InteractionMode",
    "ReadabilityLevel",
    "compute_accessibility_theta",
    "compute_usability_theta",
    "compute_cognitive_theta",
    "compute_comprehension_theta",
    "compute_task_theta",
    "compute_inclusive_theta",
    "compute_ux_accessibility_theta",
    "classify_accessibility_level",
    "classify_cognitive_load",
    "classify_usability",
    "classify_readability",
    "classify_interaction_mode",
    "UX_ACCESSIBILITY_SYSTEMS",
    "SUS_AVERAGE",
    "WCAG_AA_CONTRAST",
    "WCAG_AAA_CONTRAST",
    # Advanced Mathematics (2026)
    "MathematicalSystem",
    "MathTopologicalPhase",
    "GeometricRegime",
    "IntegrabilityLevel",
    "SymmetryType",
    "ManifoldType",
    "compute_topological_theta",
    "compute_euler_theta",
    "compute_math_curvature_theta",
    "compute_integrability_theta",
    "compute_symmetry_theta",
    "compute_homotopy_theta",
    "compute_math_theta",
    "classify_topological_phase",
    "classify_geometric_regime",
    "classify_integrability",
    "classify_symmetry",
    "MATHEMATICAL_SYSTEMS",
    "EULER_MASCHERONI",
    "MATH_FEIGENBAUM_DELTA",
    "APERY_CONSTANT",
    # High Energy Physics (2026 Phase 3)
    "HEPSystem",
    "ParticleRegime",
    "LatticeRegime",
    "ExperimentType",
    "ChiralRegime",
    "compute_qcd_coupling_theta",
    "compute_lattice_theta",
    "compute_confinement_theta",
    "compute_chiral_theta",
    "compute_hep_theta",
    "running_alpha_s",
    "classify_particle_regime",
    "classify_lattice_regime",
    "HEP_SYSTEMS",
    # Atomic/Optical Physics (2026 Phase 3)
    "AtomicOpticalSystem",
    "AtomicRegime",
    "OpticalPhase",
    "TrapType",
    "CoolingRegime",
    "compute_rabi_theta",
    "compute_cooperativity_theta",
    "compute_optical_depth_theta",
    "compute_squeezing_theta",
    "compute_cooling_theta",
    "compute_atomic_optical_theta",
    "classify_atomic_regime",
    "ATOMIC_OPTICAL_SYSTEMS",
    # Pure Mathematics (2026 Phase 3)
    "PureMathSystem",
    "AlgebraicComplexity",
    "RepresentationType",
    "FunctionalClass",
    "CombinatorialPhase",
    "compute_genus_theta",
    "compute_singularity_theta",
    "compute_rank_theta",
    "compute_spectral_theta",
    "compute_pure_math_theta",
    "classify_algebraic_complexity",
    "PURE_MATH_SYSTEMS",
    # Applied Mathematics (2026 Phase 3)
    "AppliedMathSystem",
    "PDEType",
    "OptimizationClass",
    "ConvergenceType",
    "StabilityClass",
    "compute_regularity_theta",
    "compute_stability_theta",
    "compute_convergence_theta",
    "compute_condition_theta",
    "compute_applied_math_theta",
    "classify_pde_type",
    "classify_optimization",
    "APPLIED_MATH_SYSTEMS",
    # Distributed Systems (2026 Phase 3)
    "DistributedSystem",
    "ConsistencyLevel",
    "PartitionTolerance",
    "ScalabilityClass",
    "ReplicationMode",
    "compute_consistency_theta",
    "compute_availability_theta",
    "compute_distributed_latency_theta",
    "compute_partition_theta",
    "compute_distributed_theta",
    "classify_consistency",
    "DISTRIBUTED_SYSTEMS",
    # Signal Processing (2026 Phase 3)
    "SignalSystem",
    "SignalQuality",
    "ProcessingDomain",
    "CompressionLevel",
    "FilterType",
    "compute_snr_theta",
    "compute_compression_theta",
    "compute_sparsity_theta",
    "compute_signal_theta",
    "classify_signal_quality",
    "SIGNAL_SYSTEMS",
    # Electromagnetic Spectrum
    "PhotonSystem",
    "EMBand",
    "PhotonRegime",
    "compute_em_theta",
    "compute_wavelength_theta",
    "compute_frequency_theta",
    "classify_photon_regime",
    "classify_em_band",
    "wien_displacement_wavelength",
    "planck_spectral_radiance",
    "photon_occupation_number",
    "EM_SPECTRUM",
    "SPEED_OF_LIGHT",
    "HC_EV_NM",
    "KT_300K_EV",
]
